import Vue from 'vue'
import { Search, Form, Button, Field, Toast, Icon, Loading, Image, Notify, Skeleton, Tabbar, TabbarItem, Col, Row } from 'vant'
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Form)
Vue.use(Button)
Vue.use(Field)
Vue.use(Toast)
Vue.use(Icon)
Vue.use(Loading)
Vue.use(Image)
Vue.use(Notify)
Vue.use(Skeleton)
Vue.use(Row)
Vue.use(Col)
Vue.use(Search)
